# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/louisgrante/Code/epitech-ai-solver-2021/src/gui/template/start_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.setWindowModality(QtCore.Qt.NonModal)
        window.resize(426, 384)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        window.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.label = QtWidgets.QLabel(window)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.main_layout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.main_layout.addItem(spacerItem)
        self.form = QtWidgets.QFormLayout()
        self.form.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.form.setContentsMargins(-1, 0, -1, -1)
        self.form.setVerticalSpacing(20)
        self.form.setObjectName("form")
        self.problem_label = QtWidgets.QLabel(window)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.problem_label.setFont(font)
        self.problem_label.setObjectName("problem_label")
        self.form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.problem_label)
        self.solver_label = QtWidgets.QLabel(window)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.solver_label.setFont(font)
        self.solver_label.setObjectName("solver_label")
        self.form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.solver_label)
        self.show_metrics_label = QtWidgets.QLabel(window)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.show_metrics_label.setFont(font)
        self.show_metrics_label.setObjectName("show_metrics_label")
        self.form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.show_metrics_label)
        self.show_metrics_checkbox = QtWidgets.QCheckBox(window)
        self.show_metrics_checkbox.setText("")
        self.show_metrics_checkbox.setObjectName("show_metrics_checkbox")
        self.form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.show_metrics_checkbox)
        self.problem_select = QtWidgets.QComboBox(window)
        self.problem_select.setObjectName("problem_select")
        self.form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.problem_select)
        self.solver_select = QtWidgets.QComboBox(window)
        self.solver_select.setObjectName("solver_select")
        self.form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.solver_select)
        self.main_layout.addLayout(self.form)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem1)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem2)
        self.right_button_spacer = QtWidgets.QPushButton(window)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.right_button_spacer.setFont(font)
        self.right_button_spacer.setObjectName("right_button_spacer")
        self.button_layout.addWidget(self.right_button_spacer)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_layout.addItem(spacerItem3)
        self.main_layout.addLayout(self.button_layout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.main_layout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.main_layout)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Launcher"))
        self.label.setText(_translate("window", "<html><head/><body><p><img src=\":/logo/logo.png\"/> AI Solver</p></body></html>"))
        self.problem_label.setText(_translate("window", "Select a problem"))
        self.solver_label.setText(_translate("window", "Select a solver"))
        self.show_metrics_label.setText(_translate("window", "Show metrics"))
        self.right_button_spacer.setText(_translate("window", "Start solver"))
import logo_rc
